elastic-query-service:
  version: v1

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true

user-config:
  username: test
  password: '{cipher}c716c47067f6bdc5aa317ada617700db2a6ca56963c486a2060f0522eebb04b2'
  roles: USER